# ==============================
# Системные и загрузочные конфиги
# ==============================
/etc/fstab
/etc/X11
/etc/grub.conf
/boot/grub2/grub.cfg
/etc/sysctl.conf

# ====================
# Пользователи и привилегии
# ====================
/etc/passwd
/etc/group
/etc/login.defs
/etc/nsswitch.conf
/etc/hostname
/etc/hosts
/etc/resolv.conf
/etc/network/interfaces
/etc/sysconfig/network-scripts
/etc/NetworkManager
/etc/sudoers

# ================
# Безопасность
# ================
/etc/security
/etc/selinux
/etc/pam.d
/etc/audit
/etc/rsyslog.conf
/etc/logrotate.conf

# ================
# Сервисы
# ================
/etc/nginx
/etc/httpd
/etc/mysql
/etc/postgresql
/etc/sssd
/etc/ssh/sshd_config

# ================
# Репозитории и пакеты
# ================
/etc/yum.repos.d
/etc/yum.conf
/etc/dnf/dnf.conf

# ================
# Чувствительные
# ================
#/etc/shadow
#/etc/gshadow
